# OSARA: Open Source Accessibility for the REAPER Application
# Utility to build translated NSIS installer strings
# Copyright 2026 James Teh
# License: GNU General Public License version 2.0

from ast import literal_eval
from collections import OrderedDict
import os

from installerStrings import RE_INSTALLER_STRING, escapeNsiString, unescapeNsiString


LOCALE_TO_NSIS_LANGUAGE = OrderedDict((
	("de_DE", "German"),
	("es_ES", "Spanish"),
	("es_MX", "SpanishInternational"),
	("fr_FR", "French"),
	("fr_CA", "French"),
	("nb_NO", "Norwegian"),
	("pt_BR", "PortugueseBR"),
	("ru_RU", "Russian"),
	("tr_TR", "Turkish"),
	("zh_CN", "SimpChinese"),
	("zh_TW", "TradChinese"),
))

def _parse_po_string(text):
	return literal_eval(text)


def _parse_po(path):
	entries = {}
	current = {}
	currentField = None
	with open(path, "rt", encoding="UTF-8") as input:
		for rawLine in input:
			line = rawLine.rstrip("\r\n")
			if not line:
				if current.get("msgid"):
					entries[(current.get("msgctxt"), current["msgid"])] = current.get("msgstr", "")
				current = {}
				currentField = None
				continue
			if line.startswith("#"):
				continue
			for field in ("msgctxt", "msgid", "msgstr"):
				prefix = f"{field} "
				if line.startswith(prefix):
					current[field] = _parse_po_string(line[len(prefix):])
					currentField = field
					break
				if field == "msgstr" and line.startswith("msgstr[0] "):
					current[field] = _parse_po_string(line[len("msgstr[0] "):])
					currentField = field
					break
			else:
				if not currentField or not line.startswith('"'):
					continue
				current[currentField] += _parse_po_string(line)
	if current.get("msgid"):
		entries[(current.get("msgctxt"), current["msgid"])] = current.get("msgstr", "")
	return entries


def _read_installer_strings(path):
	strings = OrderedDict()
	with open(path, "rt", encoding="UTF-8") as input:
		for line in input:
			match = RE_INSTALLER_STRING.match(line)
			if not match:
				continue
			strings[match.group("name")] = unescapeNsiString(match.group("msgid"))
	return strings


def makeInstallerStrings(target, source, env):
	targetPath = target[0].path
	os.makedirs(os.path.dirname(targetPath), exist_ok=True)
	installerPath = next(s.path for s in source if s.path.endswith(".nsi"))
	localePaths = {
		os.path.splitext(os.path.basename(s.path))[0]: s.path
		for s in source if s.path.endswith(".po")
	}
	strings = _read_installer_strings(installerPath)
	with open(targetPath, "wt", encoding="UTF-8", newline="\n") as output:
		output.write("; Auto-generated by SCons. Do not edit.\n\n")
		output.write('!insertmacro MUI_LANGUAGE "English"\n')
		seenLanguages = set()
		for language in LOCALE_TO_NSIS_LANGUAGE.values():
			if language in seenLanguages:
				continue
			seenLanguages.add(language)
			output.write(f'!insertmacro MUI_LANGUAGE "{language}"\n')
		output.write("\n")
		seenLanguages.clear()
		for locale, language in LOCALE_TO_NSIS_LANGUAGE.items():
			localePath = localePaths.get(locale)
			if not localePath or language in seenLanguages:
				# Some OSARA locales share the same NSIS language slot, so the first
				# locale in LOCALE_TO_NSIS_LANGUAGE with an available .po wins.
				continue
			seenLanguages.add(language)
			translations = _parse_po(localePath)
			for name, english in strings.items():
				key = ("installer", english)
				translated = translations[key] if key in translations else english
				output.write(
					f'LangString {name} ${{LANG_{language.upper()}}} "{escapeNsiString(translated)}"\n'
				)
			output.write("\n")
