branches:
 only:
  - master

language: objective-c

addons:
 ssh_known_hosts: duralumin.jantrid.net

env:
 - version="2020.1pre-$TRAVIS_BUILD_NUMBER,${TRAVIS_COMMIT:0:8}" dmg="osara_$version.dmg"

before_install:
 - sudo pip install scons

install:
 - cd ci
 # Decrypt files.
 - openssl enc -aes-256-cbc -d -pass pass:$encFileKey -in ssh_id_rsa.enc -out ssh_id_rsa
 # Install ssh stuff.
 - cp ssh_id_rsa ~/.ssh/id_rsa
 - chmod 600 ~/.ssh/id_rsa
 - cd ..

script: scons version=$version

after_success:
 '(echo "{\"os\": \"mac\", \"version\": \"$version\", \"dmg\": \"$dmg\"}"; cat installer/$dmg) | ssh osara@duralumin.jantrid.net osaraCiHook'
