/*
 * OSARA: Open Source Accessibility for the REAPER Application
 * Resource constants
 * Author: James Teh <jamie@jantrid.net>
 * Copyright 2015 NV Access Limited
 * License: GNU General Public License version 2.0
 */

#define IDC_STATIC -1

#define ID_PARAMS_DLG 100
#define ID_PARAM 101
#define ID_PARAM_VAL_EDIT 102
#define ID_PARAM_VAL_SLIDER 103
#define ID_PARAM_FILTER 104
#define ID_PARAM_ENVELOPE 105

#define ID_PEAK_WATCHER_DLG 200
#define ID_PEAK_TYPE 201
#define ID_PEAK_LEVEL 202
#define ID_PEAK_RESET 203
#define ID_PEAK_HOLD_DISABLED 204
#define ID_PEAK_HOLD_FOREVER 205
#define ID_PEAK_HOLD_FOR 206
#define ID_PEAK_HOLD_TIME 207
#define ID_PEAK_CHAN1 210
#define ID_PEAK_CHAN2 211
#define ID_PEAK_TRACK1 220
#define ID_PEAK_TRACK2 221

#define ID_CONFIG_DLG 300
#define ID_CONFIG_REPORT_SCRUB 301
#define ID_CONFIG_REPORT_FX 302
#define ID_CONFIG_REPORT_TRANSPORT 303
#define ID_CONFIG_REPORT_NOTES 304
#define ID_CONFIG_REPORT_TIME_MOVEMENT_WHILE_PLAYING 305
#define ID_CONFIG_REPORT_SURFACE_CHANGES 306
#define ID_CONFIG_MOVE_FROM_PLAY_CURSOR 307
#define ID_CONFIG_REPORT_MARKERS_WHILE_PLAYING 308
#define ID_CONFIG_REPORT_TRACK_NUMBERS 309

#define ID_MESSAGE_REVIEW_DLG 400
#define ID_MSGREV_TEXT 401

#define ID_FX_PRESET_DLG 500
#define ID_FXPRE_PRESET 501
#define ID_FXPRE_FILTER 502
